rootProject.name = "windfarer-parent"
include(":windfarer-v1_20_6")
include(":windfarer-v1_21_1")
include(":windfarer-v1_21_4")
include(":windfarer-v1_21_5")
include(":windfarer-v1_21_8")
include(":windfarer-v1_21_10")
include(":windfarer-v1_21_11")
include(":windfarer-api")
include(":windfarer-datapack")
include(":windfarer")
project(":windfarer-v1_20_6").projectDir = file("v1_20_6")
project(":windfarer-v1_21_1").projectDir = file("v1_21_1")
project(":windfarer-v1_21_4").projectDir = file("v1_21_4")
project(":windfarer-v1_21_5").projectDir = file("v1_21_5")
project(":windfarer-v1_21_8").projectDir = file("v1_21_8")
project(":windfarer-v1_21_10").projectDir = file("v1_21_10")
project(":windfarer-v1_21_11").projectDir = file("v1_21_11")
project(":windfarer-api").projectDir = file("api")
project(":windfarer-datapack").projectDir = file("datapack")
project(":windfarer").projectDir = file("Movecraft")
