name: Windfarer
version: ${projectVersion}
api-version: '1.21.8'
description: Previous movecraft fork, now split from mainstream! Basically movecraft with QoL, reworks and additional features!
authors:
  - DerToaster
  - goodroach
  - original work made by the APDevTeam
website: https://github.com/TTE-DevTeam/Windfarer
main: net.countercraft.movecraft.Movecraft
bootstrapper: net.countercraft.movecraft.WindfarerBootstrapper
loader: net.countercraft.movecraft.WindfarerPluginLoader
provides: [Movecraft]
permissions:
  movecraft.commands:
    default: true
    description: "Base permission for all commands"
  movecraft.commands.contacts:
    default: true
    description: "/contacts permission"
  movecraft.commands.ignore_contact:
    default: true
    description: "/ignorecontact permission"
  movecraft.commands.movecraft:
    default: op
    description: "Debug command for Windfarer, used to reload types among other things"
  movecraft.commands.directcontrol:
    default: true
    description: "Allows to toggle direct control on and off"
  movecraft.commands.scuttle.others:
    default: op
    description: "Allows to scuttle any craft"
  movecraft.commands.scuttle.self:
    default: true
    description: "Allows scuttling your own craft"
  movecraft.commands.release:
    default: true
    description: "Allows to release your own craft"
  movecraft.commands.release.others:
    default: op
    description: "Allows to release any craft"
  movecraft.manoverboard:
    default: true
    description: "Allows usage of the manoverboard command"
  movecraft.commands.pilot:
    default: op
    description: "Command to pilot crafts"
  movecraft.commands.pilot.null:
    default: op
    description: "Command to pilot null crafts"
  movecraft.commands.pilot.sinking:
    default: op
    description: "Command to pilot sinking crafts"
  movecraft.commands.pilot.npc:
    default: op
    description: "Command to pilot npc crafts"
  movecraft.commands.rotate:
    default: op
    description: "Command to mimic helm-sign interactions"
  movecraft.commands.cruise:
    default: op
    description: "Command to mimic cruise-sign interactions"
  movecraft.commands.craftreport:
    default: op
    description: "Debug command to show active crafts"
  movecraft.scuttle:
    default: op
    description: "Command to scuttle crafts"
  movecraft.scuttle.others:
    default: op
    description: "Command to scuttle other crafts than your own"
  movecraft.commands.craftinfo:
    default: true
    description: "Access to /craftinfo command"
  movecraft.commands.teleportcraft:
    default: op
    description: "Command to force teleport or move a craft around relative to its centerpoint"
  movecraft.commands.deletecraft:
    default: op
    description: "Command to release a craft and to delete all of its blocks"
#commands:
#  crafttype:
#    description: Get information on a specifc craft type
#    usage: /crafttype [type] [page]
#libraries:
#  - org.roaringbitmap:RoaringBitmap:1.0.6
