name: Windfarer
version: ${projectVersion}
api-version: '1.21.8'
description: Previous movecraft fork, now split from mainstream! Basically movecraft with QoL, reworks and additional features!
authors:
  - DerToaster
  - goodroach
  - original work made by the APDevTeam
website: https://github.com/TTE-DevTeam/Windfarer
main: net.countercraft.movecraft.Movecraft
bootstrapper: net.countercraft.movecraft.WindfarerBootstrapper
loader: net.countercraft.movecraft.WindfarerPluginLoader
provides: [Movecraft]
permissions:
  movecraft.commands:
    default: true
    description: "Base permission for all commands"
  movecraft.commands.contacts:
    default: true
    description: "/Contacts permission"
  movecraft.commands.movecraft:
    default: op
    description: "Debug command for Windfarer, used to reload types among other things"
  movecraft.commands.directcontrol:
    default: true
    description: "Allows to toggle direct control on and off"
  movecraft.commands.scuttle.others:
    default: op
    description: "Allows to scuttle any craft"
  movecraft.commands.scuttle.self:
    default: true
    description: "Allows scuttling your own craft"
  movecraft.commands.release:
    default: true
    description: "Allows to release your own craft"
  movecraft.commands.release.others:
    default: op
    description: "Allows to release any craft"
  movecraft.manoverboard:
    default: true
    description: "Allows usage of the manoverboard command"
  movecraft.commands.pilot:
    default: op
    description: "Command to pilot crafts"
  movecraft.commands.rotate:
    default: op
    description: "Command to mimic helm-sign interactions"
  movecraft.commands.cruise:
    default: op
    description: "Command to mimic cruise-sign interactions"
  movecraft.commands.craftreport:
    default: op
    description: "Debug command to show active crafts"
  movecraft.scuttle:
    default: op
    description: "Command to scuttle crafts"
  movecraft.scuttle.others:
    default: op
    description: "Command to scuttle other crafts than your own"
#commands:
#  movecraft:
#    description: base movecraft command
#    usage: /movecraft [reloadtypes]
#  release:
#    description: Releases your craft
#    usage: /release
#  pilot:
#    description: Pilots the craft at your feet
#    usage: /pilot [crafttypename]
#  ignorecontact:
#    description: Ignore a specific craft in contacts
#    usage: /ignorecontact <base craft> <craft to ignore>
#  contacts:
#    description: reports on all crafts within detection range
#    usage: /contacts <page>
#  craftreport:
#    description: reports on all active craft in the world you are in
#    usage: /craftreport <page>
#  cruise:
#    description: Starts your craft cruising
#    usage: /cruise [north|south|east|west|on|off]
#  rotate:
#    description: Rotates your craft
#    usage: /rotate [right|left]
#  manoverboard:
#    description: If enabled, returns you to a craft you have fallen out of
#    usage: /manoverboard
#  scuttle:
#    description: Sinks piloted craft
#    usage: /scuttle
#  crafttype:
#    description: Get information on a specifc craft type
#    usage: /crafttype [type] [page]
#  craftinfo:
#    description: Get information on a piloted craft
#    usage: /craftinfo [player] [page]
#libraries:
#  - org.roaringbitmap:RoaringBitmap:1.0.6
